language: python
python:
  - "2.7"
cache: pip
services:
  - postgresql
install:
  - "pip install -r requirements.txt"
  - "pip install -r requirements.test.txt"
before_script:
  - "cd client && npm install && cd .."
  - "cd client && webpack --config webpack.prod.config.js && cd .."
  - "cp modernomad/local_settings.travis.py modernomad/local_settings.py"
script: ./manage.py test modernomad core
notifications:
  slack:
    rooms:
      - embassy-network:joFu5a311yAWnrF7DQGKtl02#modernomad-notify
  email:
    recipients:
      - craig@enspiral.com
    on_success: change
    on_failure: always
