language: python
python:
  - "2.7"
cache: pip
services:
  - postgresql
install:
  - "pip install -r requirements.txt"
  - "pip install -r requirements.test.txt"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "cd client && npm install && cd .."
  - "cd client && webpack --config webpack.prod.config.js && cd .."
  - "cp modernomad/local_settings.travis.py modernomad/local_settings.py"
script: ./manage.py test modernomad core bdd
notifications:
  slack:
    rooms:
      - embassy-network:joFu5a311yAWnrF7DQGKtl02#modernomad-notify
  email:
    recipients:
      - craig@enspiral.com
      - jessy@jessykate.com
    on_success: change
    on_failure: always
addons:
  sauce_connect:
    username: "craigambrose"
    access_key: "c2c883bd-eee2-408c-905b-ef500694b928"
